### ISSUE TITLE
AutoValue toBuilder broken if @NonNullByDefault is present

### ISSUE THREAD

**Issue by frankbenoit** [google/auto#971] opened 2021-01-22 06:48 UTC
Using AutoValue 1.7.4

Given the Animal example class from the documentation.
When i add the Eclipse JDT annotation @NonNullByDefault:

````java
@NonNullByDefault // this triggers the problem
@AutoValue
public abstract class Animal {
    public abstract String name();

    public abstract int numberOfLegs();

    public static Builder builder() {
        return new AutoValue_Animal.Builder();
    }

    abstract Builder toBuilder(); // this method in combination with the @NonNullByDefault

    public Animal withName(final String name) {
        return toBuilder().setName(name).build();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder setName(String value);

        public abstract Builder setNumberOfLegs(int value);

        public abstract Animal build();
    }
}
````

Now the AutoValue_Animal class is not generated, without any message.

**Comment by eamonnmcmanus** [comment] 2021-01-25 21:09
Are you building from within Eclipse? If so, is it possible to build outside Eclipse? The "without any message" part seems like it might be a bug in Eclipse.

**Comment by kluever** [comment] 2021-01-27 14:50
FWIW, questions like this are generally better suited for StackOverflow.

**Comment by frankbenoit** [comment] 2021-01-28 04:21
I can confirm, building this with maven/tycho, the AutoValue source is generated.
Build from within Eclipse it fails.

**Comment by frankbenoit** [comment] 2021-01-28 04:58
A workaround is to deactivate the non-null-by-default for the toBuilder()

````java
@NonNullByDefault({})
abstract Builder toBuilder(); // this method in combination with the @NonNullByDefault
````
Now the generated source is created.
However, this seems to be not correct, because it should have a return value of non-null.
Hence to make this public, there must be a manual written wrapper method to fix the public API.

**Comment by frankbenoit** [comment] 2021-01-28 05:21
As this seems to be a problem of AutoValue and Eclipse-JDT playing together, I created a bug at Eclipse as well.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=570703

**Comment by eamonnmcmanus** [comment] 2021-03-18 22:39
I'm looking into this and #977. The fact that there's no error message makes it hard to know where the problem is, but I suspect it is not in AutoValue, or it is just another manifestation of #977. I'm going to close this for now, but feel free to re-open if there is something specific to look at in AutoValue other than #977.

**Closed by eamonnmcmanus** 2021-03-18 22:39 UTC
Labels: Component: value, P3, type=other
