### ISSUE TITLE
@Provided factory not supported

### ISSUE THREAD

**Issue by natros** [google/auto#336] opened 2016-05-30 13:28 UTC
I have in different packages

``` java
@AutoFactory
public class Foo {
}
```

and

``` java
@AutoFactory
public class Bar {
    public Bar(@Provided FooFactory fooFactory) {
    }
}
```

The generated factory cannot find FooFactory. There is a missing import for FooFactory or FooFactory should be fully qualified.

``` java
import javax.annotation.Generated;
import javax.inject.Inject;
import javax.inject.Provider;
@Generated("com.google.auto.factory.processor.AutoFactoryProcessor")
public final class BarFactory {
  private final Provider<FooFactory> fooFactoryProvider;
  @Inject
  public BarFactory(Provider<FooFactory> fooFactoryProvider) {
    this.fooFactoryProvider = fooFactoryProvider;
  }
  public Bar create() {
    return new Bar(fooFactoryProvider.get());
  }
}
```

I'm using auto-factory 1.0-beta3

Thanks

**Comment by tbroyer** [comment] 2016-05-30 13:30
This is a dupe of #297

**Closed** 2019-05-12 12:21 UTC
Labels: Component: factory
