### ISSUE TITLE
value: GWT serializable, list accumulation 

### ISSUE THREAD

**Issue by h908714124** [google/auto#364] opened 2016-08-01 17:25 UTC
The following doesn't compile:

``` java
@AutoValue
@GwtCompatible(serializable = true)
abstract class Animal {

    abstract ImmutableList<String> countries();

    static Builder builder() {
        return new AutoValue_Animal.Builder();
    }

    @AutoValue.Builder
    abstract static class Builder {
        abstract ImmutableList.Builder<String> countriesBuilder();
        abstract Animal build();
        Builder addCountry(String value) {
            countriesBuilder().add(value);
            return this;
        }
    }
}
```

The error is:

> com.google.auto.value.processor.escapevelocity.EvaluationException: java.util.NoSuchElementException
>       at com.google.auto.value.processor.escapevelocity.Node.evaluationException(Node.java:63)

When serializable is false, it compiles.

Also I found it surprising that the compiler generates the ImmutableList.builder() call in this case. Are there other collection libraries supported too, or only Guava?

**Comment by eamonnmcmanus** [comment] 2016-08-01 17:29
I'll see if I can reproduce this.

There is special handling for Guava's immutable collections, yes. Not for any other collection libraries currently.

**Comment by h908714124** [comment] 2016-08-01 19:14
I'm not happy that autovalue know things about Guava or other libraries. If you don't mind, I would suggest a change to the Builder API instead:

````java
@AutoValue
abstract class Animal {

    abstract ImmutableList<String> countries();

    static Builder builder() {
        // create builder and pass to constructor
        return new AutoValue_Animal.Builder(ImmutableList.builder());
    }

    @AutoValue.Builder
    abstract static class Builder {
        // PROPOSED RULE: any "non-matching" getter is added to builder constructor.
        // "xBuilder" named methods lose their special status.
        abstract ImmutableList.Builder<String> countriesBuilderBla();
        // "private"
        abstract Builder countries(ImmutableList<String> countries);
        // "private"
        abstract Animal autoBuild();
        // accumulator method
        Builder addCountry(String value) {
            countriesBuilderBla().add(value);
            return this;
        }
        // "public"
        Animal build() {
            countries(countriesBuilderBla().build());
            return autoBuild();
        }
    }
}
````

**Comment by eamonnmcmanus** [comment] 2016-08-02 15:40
We plan to generalize the rule about Guava immutable collections, so that you write
```java
@AutoValue
abstract class Foo {
  abstract Bar bar();

  @AutoValue.Builder
  abstract static class Builder {
    abstract BarBuilder barBuilder();
    ...
```
provided that we can figure out how to make a `BarBuilder`, how to make a `Bar` from a `BarBuilder`, and (if there is a `Foo.toBuilder()` method) how to make a `BarBuilder` from a `Bar`. Making a `BarBuilder` can be either `new BarBuilder()` or `Bar.builder()`. Making a `Bar` must be `barBuilder.build()`. Making a `BarBuilder` from a `Bar` can be `bar.toBuilder()`, or unfortunately (since the Guava classes don't have `toBuilder()` methods) also via `setAll` or `putAll`.

One advantage of this is that it works if `Bar` is itself a nested `@AutoValue` class with its own `@AutoValue.Builder`.

**Comment by h908714124** [comment] 2016-08-02 18:46
Right, forgot about toBuilder. In "builder constructors" scenario, this could then take the same arguments as the builder constructor. Of course, that might break compatibility, and also I think it's a bit more verbose. In any case, thanks for the update. It's good to hear that you're planning to remove the hardwiring of Guava.

**Comment by h908714124** [comment] 2016-09-30 18:46
Hello, I've been working on a project called zerobuilder that is fully compatible with auto-value. It focuses on the builder pattern and does not help define data types, so it's orthogonal to the auto-value base functionality. Please have a look and tell me what you think. Cheers!

**Comment by jbgi** [comment] 2016-09-30 19:00
(https://github.com/h908714124/zerobuilder)

**Comment by ronshapiro** [comment] 2019-04-15 13:49
Closing this as we've had some updates for Builder types. Feel free to comment if the issue persists

**Comment by eamonnmcmanus** [comment] 2019-04-15 15:01
I just tried this, and it appears the issue is still there.

**Closed** 2019-04-16 16:07 UTC
Labels: Component: value
