### ISSUE TITLE
Setting explicit annotation processor

### ISSUE THREAD

**Issue by toaderandrei** [google/auto#492] opened 2017-05-18 08:40 UTC
Hi,

I updated the android studio the latest version 3.0 and I have the following error:

```  
 Error:Execution failed for task ':sdk:javaPreCompileDebugAndroidTest'.
> Annotation processors must now be declared explicitly.  The following dependencies in the compile classpath are found to contain annotation processors.  Please add them to the annotationProcessor configuration.
    - auto-value-1.4.1.jar
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with the previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

However, if I add to the default config the following snippet:
```  
       javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
```

all works fine. 
It seems this issue has been reported for butterknife but fixed meanwhile:
https://github.com/JakeWharton/butterknife/issues/908
Is it possible to tell if there is a fix aside of the one mentioned before?

**Comment by tbroyer** [comment] 2017-05-18 11:13
The way Butterknife was "fixed" (I believe) was to split it into two artifacts: the annotations and the annotation processor. So this is basically a dupe of #268. You can actually find a separate auto-value-annotations artifact (made by… Jake Wharton ;-) ) at `com.jakewharton.auto.value:auto-value-annotations:1.4`

Something like:
```gradle
provided 'com.jakewharton.auto.value:auto-value-annotations:1.4'
annotationProcessor 'com.google.auto.value:auto-value:1.4.1'
```
_(disclaimer: I don't do Android, adjust the configuration names as needed if I got them wrong)_

**Comment by JeroenMols** [comment] 2017-05-25 09:46
@tbroyer just tried them out, names are correct

**Comment by nglorioso** [comment] 2019-08-08 20:55
Closing as #268 is fixed.

**Closed by nglorioso** 2019-08-08 20:55 UTC
Labels: P3

**Comment by Zhuinden** [comment] 2020-02-15 19:09
@nglorioso i am getting this for AutoFactory, please advise
