### ISSUE TITLE
autovalue extensions for builders

### ISSUE THREAD

**Issue by eliasbagley** [google/auto#491] opened 2017-05-12 22:15 UTC
Hi, is there any way to use the extensions API to modify the generated builder code?

**Comment by naturalwarren** [comment] 2017-05-12 22:34
Not that I'm aware of. What's the use case you're thinking of?

**Comment by JakeWharton** [comment] 2017-05-12 22:49
Dupe #349

**Comment by eamonnmcmanus** [comment] 2017-05-15 15:01
As @JakeWharton notes, this is a duplicate of #349. We should at least stop having the generated `Builder` class be final, which would allow some use cases to work.

**Closed by eamonnmcmanus** 2017-05-15 15:01 UTC
