### ISSUE TITLE
@Nullable not generated for equals(Object o)

### ISSUE THREAD

**Issue by PH0lder** [google/auto#644] opened 2018-06-20 03:16 UTC
I have my Eclipse based projects configured with ``@NonNullByDefault`` in the package-info file.  This means that all generated code included in the package (which includes AutoValue generated code because it puts itself in the same package) will assume all paramters are ``@NonNull`` by default.  This impacts the generated code for  " ``public boolean equals(Object o)`` " which should now be generated as "  ``public boolean equals(@Nullable Object o) ``" in order for the ``@Override`` to be valid.

The generated code:
```
  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof AutoValueClassTwo) {
      AutoValueClassTwo that = (AutoValueClassTwo) o;
      return (this.name.equals(that.name()))
           && (this.numberOfLegs == that.numberOfLegs());
    }
    return false;
  }
```

produces these warnings:
```
Multiple markers at this line
	- Illegal redefinition of parameter o, inherited method from Object does not constrain this 
	 parameter
	- overrides java.lang.Object.equals
```

**Comment by tbroyer** [comment] 2018-06-20 07:35
Duplicate of #73

**Comment by eamonnmcmanus** [comment] 2018-06-20 20:13
Those warnings are clearly incorrect. Every linter should know that the parameter to `equals(Object)` is `@Nullable` and that `@NonNullByDefault` shouldn't apply. As a workaround, if your `@AutoValue` class says this...

```java
@Override public abstract boolean equals(@Nullable x);
```

...and if `@Nullable` is a `TYPE_USE` annotation, then it will be copied to the parameter declaration in the implementation. Alternatively, if you are compiling against a version of `java.lang.Object` where `equals` already has this annotation, it will be copied without having to use the workaround. Is there a way to configure Eclipse like that?

@tbroyer is right to mention #73, which already captures our thinking about trying to conjure up a `@Nullable` annotation that hasn't been mentioned by the user.

**Closed by eamonnmcmanus** 2018-06-20 20:13 UTC
