### ISSUE TITLE
AutoFactory ignores @Named Annotation

### ISSUE THREAD

**Issue by confile** [google/auto#234] opened 2015-04-27 19:09 UTC
I tried to use AutoFactory and create a factory for the following class: 

```
import javax.inject.Named;

@AutoFactory(className="StartPresenterFactory")
public class StartPresenter{

@Inject
  public StartPresenter(@Provided @Named("namedValue") TestTest ttt) {
  }
}
```
The factory which is created does not include the value of the ``@Named`` annotation. Here is the result: 
```
import javax.annotation.Generated;
import javax.inject.Inject;
import javax.inject.Provider;
@Generated("com.google.auto.factory.processor.AutoFactoryProcessor")
public final class StartPresenterFactory {
      private final Provider<buddyis.TestTest> tttProvider;
     @Inject
     public StartPresenterFactory(@javax.inject.Named Provider<buddyis.TestTest> tttProvider) {
         this.tttProvider = tttProvider;
    }
}
```

As you can see ``@Named("namedValue")`` is not represented correctly by AutoFactory.

**Comment by cgruber** [comment] 2015-05-08 00:24
Duplicate of #174

**Closed by cgruber** 2015-05-08 00:24 UTC
