### ISSUE TITLE
Sporadic IOExceptions during parsedTemplateForResource

### ISSUE THREAD

**Issue by hzsweers** [google/auto#365] opened 2016-08-02 07:46 UTC
We're seeing sporadic failures during builds from AutoValue during `parsedTemplateForResource`. We're really at a loss for what's going on, and are happy to dig in to anything you want us to try. Using AutoValue 1.3-rc2, one internal custom extension being used in Android projects. They look like this (both with gradle and buck builds):

```
Caused by: java.lang.AssertionError: java.io.IOException: Stream closed

	at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:111)
	at com.google.auto.value.processor.AutoValueTemplateVars.<clinit>(AutoValueTemplateVars.java:184)
	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:441)
	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 34 more
Caused by: java.io.IOException: Stream closed

	at com.google.auto.value.processor.escapevelocity.Parser.next(Parser.java:141)
	at com.google.auto.value.processor.escapevelocity.Parser.<init>(Parser.java:84)
	at com.google.auto.value.processor.escapevelocity.Template.parseFrom(Template.java:57)
	at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:107)
	... 45 more
```

```
java.lang.RuntimeException: java.lang.AssertionError: java.io.IOException: Stream closed

	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:247)
	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:155)
	at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:154)
	at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:137)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1223)
	at com.facebook.buck.rules.CachingBuildEngine.access$4(CachingBuildEngine.java:1204)
	at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:304)
	at com.facebook.buck.rules.CachingBuildEngine$3$1.call(CachingBuildEngine.java:1)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: java.io.IOException: Stream closed

	at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:111)
	at com.google.auto.value.processor.AutoValueTemplateVars.<clinit>(AutoValueTemplateVars.java:184)
	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:441)
	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
	at com.facebook.buck.jvm.java.TracingProcessorWrapper.process(TracingProcessorWrapper.java:104)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 20 more
Caused by: java.io.IOException: Stream closed

	at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:142)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read(BufferedReader.java:182)
	at java.io.LineNumberReader.read(LineNumberReader.java:126)
	at com.google.auto.value.processor.escapevelocity.Parser.next(Parser.java:141)
	at com.google.auto.value.processor.escapevelocity.Parser.<init>(Parser.java:84)
	at com.google.auto.value.processor.escapevelocity.Template.parseFrom(Template.java:57)
	at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:107)
	... 32 more
```

**Comment by eamonnmcmanus** [comment] 2016-08-02 20:05
Is this happening with an IDE or from Maven or something else?

**Comment by hzsweers** [comment] 2016-08-02 20:06
happens in the IDE, command line, gradle, buck, locally, and on CI. All intermittently, about 10-20% of the time.

**Comment by kageiit** [comment] 2016-08-02 21:35
could be related to this jdk bug? https://bugs.openjdk.java.net/browse/JDK-6947916

**Comment by eamonnmcmanus** [comment] 2016-08-02 22:40
I'm afraid @kageiit is probably right. That's a pretty serious JDK bug, though I suppose the circumstances that trigger it must be unusual, given that it's been open since 2010. I was going to suggest that AutoValue might try to avoid triggering it by not closing the [resource](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/autovalue.vm) that it loads from the compiler classpath; but actually I see that we already [fail to do that](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/TemplateVars.java#L107), which is therefore a bug that I will avoid fixing. Does your extension also load resources from the compiler class path? Could it be changed so that it doesn't close them? I'm not sure if that might lead to a resource leak in the IDE, though.

Maybe there's also some sort of workaround based on calling [URLConnection.setUseCaches(true)](https://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#setUseCaches(boolean))?

**Comment by hzsweers** [comment] 2016-08-03 06:19
Thanks for the insight. We're disabling our extension to see if that's the root cause and will report back here with our findings.

**Comment by hzsweers** [comment] 2016-08-06 07:22
Removing our extension unfortunately didn't resolve the issue :/. We're not really sure how to proceed on this, especially considering AutoValue is so widely used. One thought I had - we have a project with nearly 100 individual gradle modules. Could there potentially be some race condition where multiple modules (compiling and running apt in parallel) are reading from a shared resource file and causing this?

**Comment by hzsweers** [comment] 2016-08-07 12:45
The longer term solution could be to get off using templates entirely. Is there any reasons to continue using them now that we have tools like JavaPoet?

**Comment by ronshapiro** [comment] 2016-08-08 14:32
https://github.com/square/javapoet/issues/77

**Comment by hzsweers** [comment] 2016-08-16 23:08
@ronshapiro @eamonnmcmanus any thoughts on my race condition suggestion with parallel modules?

**Comment by ronshapiro** [comment] 2016-08-17 14:32
@hzsweers neither of us are gradle experts by any means. Maybe try to run builds serially and see what happens?

**Comment by bsautel** [comment] 2016-08-22 16:23
I am also facing this issue in a project using SBT as build tool. I sometimes get this error in my Jenkins CI build. I think I never got this issue on my laptop.

I also noticed several times that when I encounter this issue within Jenkins, if I relaunch it (even 3 or 4 times) I still get this issue (build directory is cleaned before build). But if I update a (any?) Java file and relaunch the build, it passes, as if some particular combinations of source files provoke this issue.

Note that I upgraded `auto-value` from `1.1` to `1.2` and it did not change anything regarding this issue.

**Comment by bsautel** [comment] 2016-08-24 13:34
I don't know why but I have been facing to this issue nearly at each build since last week.

I took a look at SBT behavior and I discovered it builds modules in parallel. I just come to disable it, I will see in a few days if the issue is still here.

**Comment by eamonnmcmanus** [comment] 2016-10-01 21:39
I'm thinking as a workaround we could catch IOException and explicitly find the resource by opening the jar containing it. That's potentially slow so we wouldn't want to do it always. Meanwhile it appears that there underlying JDK bug will be fixed in JDK 9.

**Comment by hzsweers** [comment] 2016-10-02 18:48
That works for me if it's not that much slower, but I'm not sure I follow how that avoids having to stream it from the file. Something about how Java treats files in jars?

**Comment by eamonnmcmanus** [comment] 2016-10-03 00:12
The JDK bug is apparently in URLConnection, so I'm proposing an alternative path that doesn't use URLConnection. Instead we'd dissect the URL path returned by getResource in order to find the jar and the name of the entry in it. Then we'd open the jar using JarFile and find the entry that way. So no URLConnection and no JDK bug. Hopefully.

**Comment by hzsweers** [comment] 2016-10-09 00:17
Sorry for the delayed response as I've been on vacation. So I've been giving this a shot, but I don't see how we're supposed to find the jar. At runtime, all the classes are exploded into a normal directory, so there's never a jar file in the hierarchy.

```
file:/Users/zsweers/dev/java/contributing/auto/value/target/classes/com/google/auto/value/processor/autovalue.vm
/Users/zsweers/dev/java/contributing/auto/value/target/classes/com/google/auto/value/processor/autovalue.vm
/Users/zsweers/dev/java/contributing/auto/value/target/classes/com/google/auto/value/processor
/Users/zsweers/dev/java/contributing/auto/value/target/classes/com/google/auto/value
/Users/zsweers/dev/java/contributing/auto/value/target/classes/com/google/auto
/Users/zsweers/dev/java/contributing/auto/value/target/classes/com/google
/Users/zsweers/dev/java/contributing/auto/value/target/classes/com
/Users/zsweers/dev/java/contributing/auto/value/target/classes
/Users/zsweers/dev/java/contributing/auto/value/target
/Users/zsweers/dev/java/contributing/auto/value
/Users/zsweers/dev/java/contributing/auto
/Users/zsweers/dev/java/contributing
/Users/zsweers/dev/java
/Users/zsweers/dev
/Users/zsweers
/Users
/
```

Code I've been tinkering with so far:

```java
URL url = AutoValueTemplateVars.class.getResource(resourceName);
  File file = new File(url.getPath());
  printHierarchy(file);
  File jar = file.getParentFile();
  InputStream in;
  try {
    JarFile jarFile = new JarFile(jar);
    ZipEntry entry = jarFile.getEntry(resourceName);
    in = jarFile.getInputStream(entry);
  } catch (IOException e) {
    throw new AssertionError(e);
  }
```

**Comment by hzsweers** [comment] 2016-10-09 02:36
Think I've got a basic working solution in #390

**Closed** 2016-10-12 22:16 UTC
Labels: Component: value

**Comment by eamonnmcmanus** [comment] 2016-10-12 23:54
I'm interested in confirmation that #393 does in fact fix this problem. I haven't been able to reproduce the problem myself, but that fix should work given the exception shown.

**Comment by hzsweers** [comment] 2016-10-12 23:56
We can fork internally and run with this, will report back
