### ISSUE TITLE
Consider bumping java target values to 1.8, since no one runs the annotation processors on <8

### ISSUE THREAD

**Issue by cgruber** [google/auto#504] opened 2017-06-29 02:21 UTC
At this point, we're constraining the processors needlessly, insofar as Java 7 has been EOL'ed and everyone who runs javac runs it on Java8+, even if they target earlier JVMs in their actual production code.  I think AutoFactory and AutoValue (processors only, not the generated code) can reasonably start using java-8 niceties.

**Comment by eamonnmcmanus** [comment] 2017-06-29 16:21
AutoValue already does use Java 8. Are there further changes to be made there?

I agree about AutoFactory.

**Comment by ronshapiro** [comment] 2017-06-29 16:30
I think we just have to update https://github.com/google/auto/blob/d7675b21258a308f0f826c94609fb39c0b2151fc/pom.xml#L37. It looks like autovalue did that for itself, but we can do it for all of the projects.

**Comment by cgruber** [comment] 2017-06-29 16:44
Let's do it.  I'm re-writing chunks of autofactory and it's maddenning not being able to do some reasonable things without massive boilerplate.

**Comment by cgruber** [comment] 2017-06-29 16:45
I'll update it in the rewrite CL.

**Comment by elharo** [comment] 2021-01-26 13:56
Can this be closed?

**Comment by eamonnmcmanus** [comment] 2021-01-28 20:27
I just checked, and we use Java 8 everywhere except two places. One is the `gwtserializer` integration tests, where I think it's an oversight and should be fixed. The other is `auto-value-annotations`, where we effectively specify `-source 7` and that is intentional. (We require at least Java 8 to compile, but we allow you to compile with `-source 7`, so the annotations must also be compiled with `-source 7`.)

**Comment by elharo** [comment] 2021-01-28 20:51
I asked because I thought this had already been done. That is, I do have CI's that use OpenJDK 7 and they fail when we upgrade past auto 1.4.

**Comment by eamonnmcmanus** [comment] 2021-01-29 00:10
Right, that's Working As Intended. You can build with `-source 7 -target 7` if you want the built artifacts to be able to run on Java 7 (or Android), but you can't use JDK 7 to build.

**Closed** 2021-02-04 23:41 UTC
Labels: P3
