### ISSUE TITLE
autofactory: don't make generated factories final

### ISSUE THREAD

**Issue by Zubnix** [google/auto#169] opened 2015-01-01 15:26 UTC
Currently generated factories are final. This makes them very hard (almost impossible) to mock (eg using mockito). A solution is to use a 'spy', however this requires to also provide all dependencies of the spied factory, making the test very messy.

solution: don't make generated factories final.

**Comment by cgruber** [comment] 2015-01-12 17:39
Duplicate of #99. The issue is under API review inside google at this point, so we'll have some resolution soon.

**Closed by cgruber** 2015-01-12 17:39 UTC
