### ISSUE TITLE
Builders are broken with activated null-annotation analysis in Eclipse 

### ISSUE THREAD

**Issue by ChristianCiach** [google/auto#505] opened 2017-06-30 09:32 UTC
Using `@NonNullByDefault` with Eclipse breaks the creation of Builders.

Working Example:

import com.google.auto.value.AutoValue;

```
@AutoValue
abstract class TestPlanConfig {

	abstract String owner();

	static Builder builder() {
		return new AutoValue_TestPlanConfig.Builder();
	}

	@AutoValue.Builder
	abstract static class Builder {
		abstract Builder owner(String owner);

		abstract TestPlanConfig build();
	}
}
```

Not working example:

```
import org.eclipse.jdt.annotation.NonNullByDefault;

import com.google.auto.value.AutoValue;

@AutoValue
@NonNullByDefault
abstract class TestPlanConfig {

	abstract String owner();

	static Builder builder() {
		return new AutoValue_TestPlanConfig.Builder();
	}

	@AutoValue.Builder
	abstract static class Builder {
		abstract Builder owner(String owner);

		abstract TestPlanConfig build();
	}

}
```

The class "AutoValue_TestPlanConfig.Builder" doesn't get generated and there are error markers on every abstract method of the Builder, saying: 

> "Setter methods must return my.package.TestPlanConfig.Builder" 

and on the build()-method 

> "Method without arguments should be a build method returning my.package.TestPlanConfig or a getter method with the same name and type as a getter method of my.package.TestPlanConfig".

I am not sure if this is a bug in AutoValue or Eclipse, but it is probably not hard for you to workaround this either way. My guess is that the `@NonNullByDefault`-annotation modifies all return types, changing `Builder` to `@NonNull Builder` and `TestPlanConfig` to `@NonNull TestPlanConfig`.

This issue occurs on AutoValue 1.3 and 1.4.1 together with Eclipse Neon or Oxygen.

**Comment by eamonnmcmanus** [comment] 2017-06-30 17:49
Are you able to test this against 1.5-SNAPSHOT? It's conceivable that it was fixed by [this change](https://github.com/google/auto/commit/8a5286e2a33ad4d3f3e0a206f7bda045407b19ca). I'm not able to reproduce the problem with the standalone Eclipse 4.6 compiler.

**Comment by eamonnmcmanus** [comment] 2017-06-30 18:15
Never mind, I am able to reproduce the problem by invoking the compiler with `-err:nullAnnot`.

**Comment by eamonnmcmanus** [comment] 2017-06-30 23:15
On closer inspection, the problem I am seeing is different. Since `AutoValue_TestPlanConfig` doesn't have the `@NonNullByDefault` annotation, Eclipse considers its overrides to be incompatible with the ones from `TestPlanConfig`. If I explicitly add `@AutoValue.CopyAnnotations` then I get errors because the parameter to `equals(Object)` needs to be `@Nullable` and so do the fields in the generated builder. These are changes we could reasonably make.

So it does look as if the difference in what we are seeing might be due to the change I mentioned earlier. I'm interested again in knowing whether you see the same problem with 1.5-SNAPSHOT or different ones.

**Comment by eamonnmcmanus** [comment] 2017-07-01 00:09
I hacked in a change to fix the problems I mentioned above, but what I see now is that my builder looks like this:

```java
  static final class Builder extends TestPlanConfig.Builder {
    private @org.eclipse.jdt.annotation.Nullable String owner;
    Builder() {
    }
    @Override
    TestPlanConfig.Builder owner(String owner) {
      if (owner == null) {
        throw new NullPointerException("Null owner");
      }
      this.owner = owner;
      return this;
    }
    @Override
    TestPlanConfig build() {
      String missing = "";
      if (this.owner == null) {
        missing += " owner";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_TestPlanConfig(
          this.owner);
    }
  }
```

Unfortunately Eclipse is unable to see that this line can't be reached if `this.owner` is null:

```java
      return new AutoValue_TestPlanConfig(
          this.owner);
```

I tried changing the generated code so it looks like this:

```java
    TestPlanConfig build() {
      if (this.owner == null) {
        String missing = "";
        if (this.owner == null) {
          missing += " owner";
        }
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_UseNonNullByDefault(
          this.owner);
    }
```

Unfortunately Eclipse isn't clever enough to see that `this.owner` can't be null at the end, and still says this:

```
2. ERROR in /.../AutoValue_TestPlanConfig.java (at line 71)
	this.owner);
	^^^^^^^^^^
Null type mismatch: required '@NonNull String' but the provided value is specified as @Nullable
```

I imagine that this is fixable (perhaps by generating `(@NonNull String) this.owner`, but I'm not convinced it's worth all this effort. I'm inclined to say that AutoValue classes shouldn't be marked `@NonNullByDefault`.

**Comment by ChristianCiach** [comment] 2017-07-01 11:49
Thanks for your quick response! I will give detailed feedback when I am at work next Monday. 

But please keep in mind that `@NonNullByDefault` is usually applied to the package and not to specific classes. This makes it difficult to exclude AutoValue classes from this annotations. But I still think that it is the right thing to apply this annotation to AutoValue classes, too, because, well, they are indeed non null by default.

**Comment by ChristianCiach** [comment] 2017-07-01 12:33
Unfortunately the issue is not fixed with 1.5-SNAPSHOT :(

![autovalue_issue](https://user-images.githubusercontent.com/19341644/27762075-3feff524-5e6a-11e7-821d-92a628f9480b.png)

**Comment by ChristianCiach** [comment] 2017-07-01 12:38
> Unfortunately Eclipse isn't clever enough to see that this.owner can't be null at the end

Yes, Eclipse is stupid in this regard, see here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=414237

But it is very easy to circumvent this "problem" (well, eclipse is not entirely wrong here) by copying the field to a local variable first, and then checking the local variable for null.

**Comment by ChristianCiach** [comment] 2017-07-03 10:29
Unfortunately I cannot provoke the error with the message ""Setter methods must return..." when using the Eclipse batch compiler. The issue seems to appear only when using the Eclipse IDE.

**Comment by ChristianCiach** [comment] 2017-07-03 11:41
This is extremely difficult to debug, as I don't know how to use the debugger for an annotation processor when used with the Eclipse Compiler.

But I think I found the problem: The error message "Setter methods must return ..." is reported at `BuilderMethodClassifier.classifyMethodOneArg(ExecutableElement)` if `TYPE_EQUIVALENCE.equivalent(builderMethodReturnType(method), builderType.asType())` returns false. I think this happend because the annotationMirrors of both parameters are different:
* `builderMethodReturnType(method).getAnnotationMirrors()` returns `[@org.eclipse.jdt.annotation.NonNull]`
* `builderType.asType().getAnnotationMirrors()` returns `[]` (empty list)

**Comment by ChristianCiach** [comment] 2017-07-03 12:17
`auto.common.MoreTypes.EqualVisitor.visitDeclared(...)` tests if `aElement.equals(bElement)`. `org.eclipse.jdt.internal.compiler.apt.model.ElementImpl.equals(..)` (see [here](https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.compiler.apt/src/org/eclipse/jdt/internal/compiler/apt/model/ElementImpl.java)) has an interesting comment:

> // TODO: equals() implemented as == of JDT bindings.  Valid within
> // a single Compiler instance; breaks in IDE if processors cache values. 

The `bindings` seem to include the type annotations. I think this is as far as I can get with my non-existing debugging tools. 

Is this something that auto-value can workaround?

**Comment by ChristianCiach** [comment] 2017-07-03 12:41
Super ugly workaround:

```
import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.jdt.annotation.NonNullByDefault;

import com.google.auto.value.AutoValue;

@AutoValue
@NonNullByDefault
abstract class TestPlanConfig {

	abstract String owner();

	@AutoValue.Builder
	@NonNullByDefault({})
	interface Builder {

		Builder owner(@NonNull String owner);

		TestPlanConfig build();
	}
}
```

**Comment by ChristianCiach** [comment] 2017-07-05 08:39
The more I think about this, the more I come to the conclusion that this is a bug in auto-value or auto-common. `com.google.auto.common.MoreTypes.equivalence()` was very likely not written with Java 8 [type annotations](https://docs.oracle.com/javase/tutorial/java/annotations/type_annotations.html) in mind. The correct title of this issue should probably be "Builder-generation is broken when type annotations are used".

This issue is probably not specific to `@org.eclipse.jdt.annotation.NonNull", although this may be the most prominent type annotation of the moment.

If `MoreTypes.equivalence()` is too strict and should ignore type annotations, then this would be an issue with auto-common. Otherwise auto-value should not use `MoreTypes.equivalence()` to compare the type of `@NonNull Builder setterMethod(String)` and `class Builder`, because  `@NonNull Builder setterMethod(String)` is valid java, but `class @NonNull Builder` is not,  so it is impossible to make these types compatible to `MoreTypes.equivalence()`.

**Comment by eamonnmcmanus** [comment] 2019-05-10 00:11
I've spent some time at last investigating this problem. I think it is a bug in Eclipse. What I observe is what I see as incorrect behaviour on [this line](https://github.com/google/auto/blob/5ff5e37a22d0b439c963b2e079832338b5dad825/common/src/main/java/com/google/auto/common/MoreTypes.java#L203)

```java
    public Boolean visitDeclared(DeclaredType a, EqualVisitorParam p) {
      if (p.type.getKind().equals(DECLARED)) {
        DeclaredType b = (DeclaredType) p.type;
        Element aElement = a.asElement();
        Element bElement = b.asElement();
        ...
        return aElement.equals(bElement)  ←— THIS LINE
        ...
```

When asked to compare the `DeclaredType` for the `Builder` type and for the return type of a method returning `@NonNull Builder` (where `@NonNull` is a `TYPE_USE` annotation), it reports false. There's no justification for that: the `Element` in each case should be the `Builder`; the annotation belongs to the type use, not to the element. This is confirmed by `getAnnotationMirrors()` returning an empty list for both elements.

We might be able to get away with comparing the qualified name of each element instead of the elements themselves. That's an ugly workaround, but appears to get past the immediate problem. I'll see whether it causes any other problems.

**Comment by eamonnmcmanus** [comment] 2019-05-11 23:09
I was able to reproduce this problem with the 4.6 compiler, but with the 4.11 compiler it seems to work fine. So I think we can close this issue.

**Closed by eamonnmcmanus** 2019-05-11 23:09 UTC
